/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import clases.Cliente;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author omara
 */
public class LISTAEMPLEADOS extends javax.swing.JFrame {

    /**
     * Creates new form LISTAEMPLEADOS
     */
    public LISTAEMPLEADOS(ResultSet resultadosConsulta, CREARESERVAS crearReserva) throws SQLException {
        initComponents();
        this.crearReserva = crearReserva;
        rellenarDatosTabla(resultadosConsulta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SeleccionarClienteButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientesTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SeleccionarClienteButton.setText("Seleccionar");
        SeleccionarClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarClienteButtonActionPerformed(evt);
            }
        });

        clientesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id_cliente", "Nombre", "Apellido", "Correo", "Numero"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(clientesTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(SeleccionarClienteButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SeleccionarClienteButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeleccionarClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarClienteButtonActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = clientesTable.getSelectedRow();
       
        if(filaSeleccionada==-1){
            JOptionPane.showMessageDialog(null, "Por favor, seleccione una fila", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int idCliente = (int) clientesTable.getValueAt(filaSeleccionada, 0);
        String nombre = (String) clientesTable.getValueAt(filaSeleccionada, 1); // Supongamos columna 1 es "nombre"
        String apellido = (String) clientesTable.getValueAt(filaSeleccionada, 2); // Columna 2 es "apellido"
        String correo = (String) clientesTable.getValueAt(filaSeleccionada, 3); // Columna 3 es "correo"
        String numero = (String) clientesTable.getValueAt(filaSeleccionada, 4); // Columna 4 es "número"

        // Creación del objeto Cliente usando los datos obtenidos
        Cliente cliente = new Cliente(nombre, apellido, correo, numero);
        cliente.setId_cliente(idCliente);

        // Asignación a textFieldCliente en la clase CREARRESERVAS
        crearReserva.setClienteSeleccionado(cliente);
        dispose();

    }//GEN-LAST:event_SeleccionarClienteButtonActionPerformed

    private void rellenarDatosTabla(ResultSet resultados) throws SQLException{
        DefaultTableModel modelo =(DefaultTableModel)clientesTable.getModel();
        modelo.setRowCount(0);
        while(resultados.next()){
            int id_cliente=resultados.getInt("Id_cliente");
            String nombre=resultados.getString("Nombre");
            String apellido=resultados.getString("Apellido");
            String correo=resultados.getString("Correo");
            String numero=resultados.getString("Numero");
            modelo.addRow(new Object[]{id_cliente,nombre,apellido,correo,numero});
        }
        
        
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LISTAEMPLEADOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LISTAEMPLEADOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LISTAEMPLEADOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LISTAEMPLEADOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LISTAEMPLEADOS().setVisible(true);
//            }
//        });
//    }

    private CREARESERVAS crearReserva;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SeleccionarClienteButton;
    private javax.swing.JTable clientesTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
